#! /bin/bash
#export PS1='[\u@\h:\w ]$ '
function parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PATH="$PATH:/vol/proj/olympus/work/sw/svenkatraman/stuff/texlive/2016/bin/x86_64-linux/"

#export PS1="\[\e[0;36m\]$(parse_git_branch)\[\e[m\]\[\e[0;32m\][\h:\w]\[\e[m\] \[\e[0;37m\]\n-> \[\e[m\]\[\e[0m\]"
export PS1="\[\033[33m\$(parse_git_branch)\[\033[00m\][\h:\[\033[32m\]\w]\n-> \[\e[m\]\[\e[0m\]"

# User specific aliases and functions (in .bashrc)


alias c="source ~/.bashrc"

alias tags="find . \( -name '[^.]*.[chlyCGHL]' \) -print > cscope.files; find . -name '*.py' -print >> cscope.files; cscope -buk -F cscope.files;"
alias tags++="find . -name '*.c' -print > cscope.files && find . -name '*.cc' -print >> cscope.files && find . -name '*.C' -print >> cscope.files && find . -name '*.hpp' -print >> cscope.files && find . -name '*.h' -print >> cscope.files && find . -name '*.cpp' -print >> cscope.files && find . -name '*.h.gen' -print >> cscope.files  && cscope -buk -F cscope.files;"
alias tags1++="find . -path ./build -prune -o -name '*.c' -print > cscope.files && find . -path ./build -prune -o -name '*.cc' -print >> cscope.files && find . -path ./build -prune -o -name '*.hpp' -print >> cscope.files && find . -path ./build -prune -o -name '*.h' -print >> cscope.files && find . -path ./build -prune -o -name '*.cpp' -print >> cscope.files && find . -path ./build -prune -o -name '*.h.gen' -print >> cscope.files  && cscope -buk -F cscope.files;"
alias vncstart='vncserver  -geometry 1920x1080 -depth 16'
alias vncstop='vncserver -kill :$*'
alias l='ls --color -l'

alias ga='git add -u'
alias go='git co '
alias gc='git commit -m '
alias gp='git push origin '
alias gm='git checkout master '
alias gpr='git pull --rebase'
alias gs='git status'
alias gsta='git stash'
alias gpop='git stash pop'
alias gd='git diff --staged'
alias gb='git branch'
alias gch='git diff --staged > changes.diff'
alias g='cat ~/.bashrc_USER|grep git'
alias gcch='git log -1 | grep commit | awk "{ print $2 }" | xargs -n 1 git show >& changes.diff'
alias gclean='git branch | grep -v " master" | grep -v ^* | xargs git branch -D'
alias gcch='git branch | grep ^* | cut -d " " -f2 | xargs -n 1 git diff origin/master >& changes.diff'
function gbn() {
    git checkout -b $1 origin/master
}
function gco() {
    git checkout -b $1 origin/$1
}
function gri() {
    git rebase -i HEAD~$1
}
function gup() {
    git checkout -b $1 origin/$1
    git rebase origin/master
    git push -f origin $1
    git checkout master
    git branch -D $1
}
alias gbd='git push origin --delete '
alias gpf='git push -f origin '
alias gws='git rebase HEAD~1 --whitespace=fix'
alias grb='git for-each-ref --format=" %(authorname) %09 %(refname)" '
alias grbm='git for-each-ref --format=" %(authorname) %09 %(refname)" | grep Chetan | grep cm'
alias gf='git fetch origin -p'
alias gro='git rebase origin/master'

alias gro12='git rebase origin/IVM_REL_0_12'
alias gro14='git rebase origin/IVM_REL_0_14'

alias gcch12='git branch | grep ^* | cut -d " " -f2 | xargs -n 1 git diff origin/IVM_REL_0_12 >& changes.diff'
function gbn12() {
    git checkout -b $1 origin/IVM_REL_0_12
}
function gup12() {
    git checkout -b $1 origin/$1
    git rebase origin/IVM_REL_0_12
    git push -f origin $1
    git checkout master
    git branch -D $1
}
alias gcch14='git branch | grep ^* | cut -d " " -f2 | xargs -n 1 git diff origin/IVM_REL_0_14 >& changes.diff'
function gbn14() {
    git checkout -b $1 origin/IVM_REL_0_14
}
function gup14() {
    git checkout -b $1 origin/$1
    git rebase origin/IVM_REL_0_14
    git push -f origin $1
    git checkout master
    git branch -D $1
}
alias grok8='git rebase origin/k8_master'

alias gcchk8='git branch | grep ^* | cut -d " " -f2 | xargs -n 1 git diff origin/k8_master >& changes.diff'
function gbnk8() {
    git checkout -b $1 origin/k8_master
}
function gupk8() {
    git checkout -b $1 origin/$1
    git rebase origin/k8_master
    git push -f origin $1
    git checkout master
    git branch -D $1
}
alias grok8='git rebase origin/k8_master'

function __build_cscope_files()
{
    find ./ -name '*.py' > cscope.files
    find ./ -name '*.h' >> cscope.files
    find ./ -name '*.c' >> cscope.files
    find ./ -name '*.C' >> cscope.files
    find ./ -name '*.H' >> cscope.files
    find ./ -name '*.cpp' >> cscope.files
    find ./ -name '*.hpp' >> cscope.files
}

function __build_cscope()
{
    echo "Building cscope for $1"
    __build_cscope_files
    cscope -Rb
}

function mkcscope()
{
    __build_cscope
}


#! /bin/bash

function mkws_old()
{
    GITURL="https://git.corp.innovium.com/"

    echo "`date` : Cloning repos..."

    git clone -q ${GITURL}/sw/ifcs.git;             echo "`date` :    'ifcs'"
    git clone -q ${GITURL}/sw/pen.git;              echo "`date` :    'pen'"
    git clone -q ${GITURL}/sw/common.git;           echo "`date` :    'common'"
    git clone -q ${GITURL}/sw/system_test.git;      echo "`date` :    'system_test'"
    git clone -q ${GITURL}/refModel/model.git;      echo "`date` :    'model'"
    git clone -q ${GITURL}/refModel/model_test.git; echo "`date` :    'model_test'"
    git clone -q ${GITURL}/sw/inno_projects.git;    echo "`date` :    'inno_projects'"

    echo ""
}

function mkws()
{
    if [ -z $1 ]; then
        echo "Usage: mkws <wsdirname>"
        return -1
    fi
    /home/builder/inno_projects/ipm -ci SDK_with_model $1
    cd $1
    git clone https://git.corp.innovium.com/factory_profiles/olympus_fp.git
    git clone https://git.corp.innovium.com/sw/aapl.git
    cp ~/.git.pre-commit ifcs/.git/hooks/pre-commit

    chmod 777 .

#    git clone https://git.corp.innovium.com/refModel/model_test.git
#    git clone https://git.corp.innovium.com/factory_profiles/olympus_fp.git
#    git clone https://git.corp.innovium.com/sw/ifcssai.git
#    git clone https://git.corp.innovium.com/arch/dps.git
#    git clone https://git.corp.innovium.com/sw/ixnetwork.git
#    cp ~/.git.pre-commit ifcs/.git/hooks/pre-commit
#    rm ~/proj_logs.txt
}


function k2mkws()
{
    if [ -z $1 ]; then
        echo "Usage: k2mkws <wsdirname>"
        return -1
    fi
    /home/builder/inno_projects/ipm -ci SDK_with_k2_model $1
}

function mkifcs()
{
    git clone https://git.corp.innovium.com/sw/ifcs.git
    cp ~/.git.pre-commit ifcs/.git/hooks/pre-commit
}

function lsc()
{
    pushd .
    for i in `/bin/ls -1 $WORKSPACE/`
    do
        cd $WORKSPACE//$i
        if [ -d ".git" ]; then
            echo "List changeset for $i"
            git status $* -uno
            echo ""
        fi
    done
    popd
}

function gbma()
{
    pushd .
    for i in `/bin/ls -1 $WORKSPACE/`
    do
        cd $WORKSPACE//$i
        if [ -d ".git" ]; then
            echo "List of My branches for $i"
            git for-each-ref --format="%(committerdate) %09 %(authorname) %09 %(refname)" | sort -k5n -k2M -k3n -k4n | grep Chetan
            echo ""
        fi
    done
    popd
}

function rsed()
{
    find ./ -type f -exec sed -i -e "s/$1/$2/g" {} \;
}
export JOBNUM=32

function f()
{
    find . -name $1
}

alias bl='bugzilla --nosslverify --bugzilla bugz.corp.innovium.com --username cmurthy login '
alias bugs='bugzilla --nosslverify --bugzilla bugz.corp.innovium.com query -a cmurthy@innovium.com -s CONFIRMED'
